cf942050-e942-4990-a113-e3df70b289be:
  attributes:
    level: 100
    points: 0
    vitality: 43
    strength: 1
    stamina: 21
    maxEnergy: 625.0
    currentEnergy: 625.0
    attributePoints: 100
