cf942050-e942-4990-a113-e3df70b289be:
  attributes:
    level: 4
    exp: 0
    exp2NextLevel: 100
    attributePoints: 0
    vitality: 0
    strength: 0
    arcane: 3
    stamina: 0
    currentEnergy: 100.0
    maxEnergy: 100.0
    currentOverhealth: 30.0
    maxOverhealth: 30.0
