name: NMLAttributes
version: '1.0-SNAPSHOT'
main: io.github.Gabriel.NMLAttributes.NMLAttributes
api-version: '1.21'
authors: [ Gabriel Nicolas ]
description: Plugin for the attributes of the No Man's Land server
commands:
  attributes:
    description: opens the attributes menu
    usage: /<command>
  levelUp:
    description: opens up the level up menu
    usage: /<command>
  setLevel:
    description: sets the player's level
    usage: /<command> <mod>
  resetProfile:
    description: resets the player's profile
    usage: /<command>