name: NMLAttributes
version: '1.0'
main: io.github.NoOne.NMLAttributes.NMLAttributes
api-version: '1.21.8'
depend:
  - NMLPlayerStats
  - NMLSkills
commands:
  levelUp:
    description: opens the level up (attributes) menu
    usage: /<command>